### ISSUE TITLE
Write smart contract and front end code

### ISSUE THREAD

**Issue by ToJen** [BlockchainNL/Simple-dApp#1]
*Will be the demo used during the inaugural meetup*

## Structure will be:
- smart contract - `solidity`
- frontend - `web3` + `react/vanilla`
- framework - `truffle`

## TODO:
- `README.md`
- wiki?
- **_moon_**

### Watching:
@ScottStevenson @jthetzel @tfrench93 @AndrewWay @moustafaelsisy @smuojeke

**Comment by jthetzel** [comment]
this following the hello world voting app tutorial, or something novel ( https://medium.com/@mvmurthy/full-stack-hello-world-voting-ethereum-dapp-tutorial-part-1-40d2d0d807c2 )?

**Comment by ToJen** [comment]
@jthetzel yes the voting app is a good tutorial. The event might only have time for 10-15 minutes of live-action coding so I was thinking of a demo that creates a custom token and then has a frontend to send it to friends. Maybe we'll call it **_MUNcoin_** 😂

**Comment by ToJen** [comment]
- Created token and escrow smart contract as well as front end to interact with token contract.
- Created tests.
